### ISSUE TITLE
Feature: User can log in

### ISSUE THREAD

**Issue by Courtney-Lippman** [streamr-turing/streamr-fe#9]
As a user, when I visit the login page, I want to put in a username and password so I can log in to the application using my credentials. 

![Image](https://user-images.githubusercontent.com/104169837/216779934-95d810fe-a384-4051-bcd7-23e68a64a1a7.png)

Subtasks:

- [x] Create a login component (should contain username and password fields)
- [x] Create a Route for the login page
- [x] User should be redirected to the homepage after successful login
- [x] If an incorrect user or password is typed, the user should see a message Oops, we cannot find that username/password. Please try again.

**Comment by Courtney-Lippman** [comment]
*** I discussed this with my mentor last night, and he encouraged us to do a login page. The reason was that it would look more professional, which we may want to consider if we put this project on our resume. *** I'll be bringing this up in our next team standup! I can't wait to discuss this with the group! 🙂 ***

**Comment by Courtney-Lippman** [comment]
We discussed Login Page as a group, and we all decided to do a login page with usernames. The password will be the same for all users for ease of demo purposes.

**Comment by Courtney-Lippman** [comment]
It might be nice to create the login page last so that we do not have to continue to log in. Thoughts? @streamr-turing/frontend

**Comment by sam-rice** [comment]
I was also wondering about the order of introducing the login page. I'm still not sure what the best way to go would be. My thought process so far for one way to handle this:

- whichever user is logged in will need to be held in state at all times so that we see/interact with the correct data at all times. ~~Using `useContext` is probably outside this project's scope, so it will probably need to be held in `App`?~~
  - edit: after some more research, I think `useContext` will make this a lot easier and requires a lot less boilerplate than I thought. Would be great to have a discussion about it tomorrow as a group.
- I think if we hard-code a user onto state while in development, we should be able to jump around without the login page getting in the way—so we could build the login page at any point.
- Once we hook up the server and want to use the login page, we can have a conditional that redirects from the root (homepage) to /login whenever the `currentUser` state is `null`, and set `currentUser` to `null` by default/on page load. 
- Once the user logs in, `currentUser` state is updated accordingly and we navigate to the root and everything works as it should for that user.
- As I'm typing this, I'm realizing that there should probably be a "log out" button on the side bar.

Curious to hear your guys' thoughts.
